version: "3.8"

services:
  front:
      build:
        context: .
        dockerfile: Dockerfile
      hostname: front
      container_name: front
      restart: 'always'
      ports:
          - "3000:3000"
      networks:
        - webserver_network

networks:
  webserver_network:
    external: true